language: go
go:
- 1.x
install:
- go get -t ./...
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- make test
after_success:
- $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci
notifications:
  email: false
