language: go
go:
- 1.x
before_install:
- git lfs pull
install:
- go get -t ./...
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
script:
- make test
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
