language: go
go:
  - 1.x

env:
  - GO111MODULE=on

before_install:
  - git lfs pull

install:
  - go get -t ./...

script:
  - make test

after_success:
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci

notifications:
  email: false
