language: go
go:
  - 1.x

env:
  - GO111MODULE=on DEFAULT_DATA_PATH=~/build/ldsec/medco-loader/data/

before_install:
  - cd ~/build/ldsec/medco-loader/data
  - bash download_test_data.sh

install:
  - go get -t ./...

script:
  - cd ~/build/ldsec/medco-loader
  - make test

after_success:
  - $GOPATH/bin/goveralls -coverprofile=profile.cov -service=travis-ci

notifications:
  email: false
