version: '3.5'
services:
  medco-loader:
    image: medco/medco-loader:dev
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    volumes:
      - ~/medco-loader/data/genomic:/dataset
      - ~/medco-deployment/configuration-profiles/dev-local-3nodes:/medco-configuration
    network_mode: host
    environment:
      - LOG_LEVEL=3
      - UNLYNX_GROUP_FILE_PATH=/medco-configuration/group.toml
      - UNLYNX_GROUP_FILE_IDX=0
      - I2B2_DB_HOST=localhost
      - I2B2_DB_PORT=5432
      - I2B2_DB_NAME=i2b2medcosrv0
      - I2B2_DB_USER=i2b2
      - I2B2_DB_PASSWORD=i2b2
      - MC_DB_HOST=localhost
      - MC_DB_PORT=5432
      - MC_DB_NAME=medcoconnectorsrv0
      - MC_DB_USER=medcoconnector
      - MC_DB_PASSWORD=medcoconnector
    command: >-
      -debug 2 v0 --group /medco-configuration/group.toml --entryPointIdx 0
      --ont_clinical /dataset/tcga_cbio/clinical_data.csv --sen /dataset/sensitive.txt
      --ont_genomic /dataset/tcga_cbio/videodemo_mutation_data.csv --clinical /dataset/tcga_cbio/clinical_data.csv
      --genomic /dataset/tcga_cbio/videodemo_mutation_data.csv --output /dataset/ --dbHost localhost --dbPort 5432
      --dbName i2b2medcosrv0 --dbUser i2b2 --dbPassword i2b2

